[sinks.s3_archives]
inputs          = ["json_parser"]    
type            = "aws_s3"
region          = "%%AWS_REGION%%"
bucket          = "%%AWS_S3_BUCKET%%"
key_prefix      = "%%AWS_S3_PREFIX%%year=%Y/month=%m/day=%d/hour=%H/"
compression     = "gzip"               # compress final objects
framing.method  = "newline_delimited"  # new line delimited...
encoding.codec  = "json"               # ...JSON
batch.max_bytes = %%S3_BATCH_MAX_BYTES%%
batch.timeout_secs = %%S3_BATCH_TIMEOUT_SECS%%
acknowledgements.enabled = false
